
logger:
    file: /opt/open5gs/var/log/open5gs/mme.log

mme:
    freeDiameter: /opt/open5gs/etc/freeDiameter/mme.conf
    s1ap:
      - dev: eth1
    gtpc:
      - dev: eth2
    gummei:
      plmn_id:
        mcc: 999
        mnc: 70
      mme_gid: 2
      mme_code: 1
    tai:
      plmn_id:
        mcc: 999
        mnc: 70
      tac: 1
    security:
        integrity_order : [ EIA2, EIA1, EIA0 ]
        ciphering_order : [ EEA0, EEA1, EEA2 ]
    network_name:
        full: Open5GS
    mme_name: mme

sgwc:
    gtpc:
      - addr: 172.25.20.3

smf:
  gtpc:
    - addr: 172.25.20.4

parameter:
max:
usrsctp:
time:
