
logger:
    file: /opt/open5gs/var/log/open5gs/smf.log

sbi:
    server:
      no_tls: true
      cacert: /opt/open5gs/etc/open5gs/tls/ca.crt
      key: /opt/open5gs/etc/open5gs/tls/smf.key
      cert: /opt/open5gs/etc/open5gs/tls/smf.crt
    client:
      no_tls: true
      cacert: /opt/open5gs/etc/open5gs/tls/ca.crt
      key: /opt/open5gs/etc/open5gs/tls/smf.key
      cert: /opt/open5gs/etc/open5gs/tls/smf.crt

smf:
    sbi:
      - dev: eth5
        port: 7777
    pfcp:
      - dev: eth3
    gtpc:
      - dev: eth1
    gtpu:
      - dev: eth2
    subnet:
      - addr: 10.45.0.1/16
      - addr: 2001:db8:cafe::1/48
    dns:
      - 8.8.8.8
      - 10.171.8.4
      - 2001:4860:4860::8888
      - 2001:4860:4860::8844
    mtu: 1400
    ctf:
      enabled: auto
    freeDiameter: /opt/open5gs/etc/freeDiameter/smf.conf

scp:
    sbi:
      - addr: 172.25.70.200
        port: 7777

nrf:
    sbi:
      - addr: 172.25.70.10
        port: 7777

upf:
    pfcp:
      - addr: 172.25.40.7

parameter:
max:
time:
