
logger:
    file: /opt/open5gs/var/log/open5gs/upf.log

upf:
    pfcp:
      - dev: eth2
    gtpu:
      - dev: eth1
    subnet:
      - addr: 10.45.0.1/16
        dnn: internet
      - addr: 2001:db8:cafe::1/48
        dnn: internet

smf:
    pfcp:
      - addr: 172.25.40.4

parameter:
max:
time:
